- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nginx

- name: Copy nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/conf.d/

- name: Restart nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx

- name: Test
  template:
    src: ./files/nginx.conf.j2
    dest: /home/ubuntu/nginx.conf