- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nginx

- name: Copy nginx.conf
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf

- name: Restart nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
