- name: Add PPT
  apt_repository:
    repo: ppa:ethereum/ethereum
    state: present

- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ethereum

- name: Copy genesis.json
  copy:
    src: files/genesis.json
    dest: /etc/geth.service/

- name: Copy shell scripts
  copy:
    src: "{{ item }}"
    dest: /etc/geth.service/
    mode: "0744"
  with_fileglob:
    - "files/*.sh"

- name: Copy geth.service
  copy:
    src: files/geth.service
    dest: /etc/systemd/system


- name: Copy text file
  copy:
    src: "{{ item }}"
    dest: /etc/geth.service/
  with_fileglob:
    - "files/*.txt"

- name: Start geth.service
  systemd:
    state: restarted
    daemon_reload: yes
    name: geth.service