- name: Add PPT
  apt_repository:
    repo: ppa:ethereum/ethereum
    state: present

- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ethereum

- name: Copy genesis.json
  copy:
    src: files/genesis.json
    dest: /home/ubuntu


- name: Copy geth.service
  copy:
    src: files/geth.service
    dest: /etc/systemd/system